language: ruby
rvm:
  - 2.3.0
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rubocop --fail-level=W
  - bundle exec rspec spec/
